name: CI

on:
  push:
    branches:
      - main
      - angular
      - react
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - uses: nrwl/nx-set-shas@v4

      # ===== CI checks & Build =====
      - run: npx nx-cloud record -- nx format:check
      - run: npx nx affected -t=lint,build --configuration=production

      # ===== DEPLOY: Shell (main) =====
      - name: Deploy Shell to S3
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cp dist/apps/shell/assets/module-federation.manifest.prod.json dist/apps/shell/assets/module-federation.manifest.json
          aws s3 sync dist/apps/shell s3://antra-lms-shell --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # ===== DEPLOY: Angular Remote =====
      - name: Deploy Angular Remote to S3
        if: github.ref == 'refs/heads/angular' && github.event_name == 'push'
        run: |
          aws s3 sync dist/apps/angular s3://antra-lms-angular --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # ===== DEPLOY: React Remote =====
      - name: Deploy React Remote to S3
        if: github.ref == 'refs/heads/react' && github.event_name == 'push'
        run: |
          aws s3 sync dist/apps/react s3://antra-lms-react --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}