name: CI

on:
  push:
    branches:
      - main
      - angular
      - react
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - uses: nrwl/nx-set-shas@v4

      # ===== CI checks =====
      - run: npx nx-cloud record -- nx format:check
      
      - run: npx nx run-many -t lint,build --configuration=production

      # ===== DEPLOY: Shell (main only) =====
      - name: Deploy Shell to S3
        if: github.ref == 'refs/heads/main'
        run: |
          cp dist/apps/shell/assets/module-federation.manifest.prod.json \
             dist/apps/shell/assets/module-federation.manifest.json
          aws s3 sync dist/apps/shell s3://antra-lms-shell --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # ===== DEPLOY: Angular Remote (main OR angular) =====
      - name: Deploy Angular Remote to S3
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/angular'
        run: |
          aws s3 sync dist/apps/angular s3://antra-lms-angular --delete --exclude "remoteEntry.mjs"
          aws s3 cp dist/apps/angular/remoteEntry.mjs \
            s3://antra-lms-angular/remoteEntry.mjs \
            --cache-control "max-age=0, no-cache, no-store, must-revalidate"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # ===== DEPLOY: React Remote (main OR react) =====
      - name: Deploy React Remote to S3
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/react'
        run: |
          aws s3 sync dist/apps/react s3://antra-lms-react --delete --exclude "remoteEntry.js"
          aws s3 cp dist/apps/react/remoteEntry.js \
            s3://antra-lms-react/remoteEntry.js \
            --cache-control "max-age=0, no-cache, no-store, must-revalidate"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
